name: Daily News Scraper

on:
  schedule:
    - cron: "0 12 * * *"  # runs every day at 12:00 UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scrapy vaderSentiment transformers torch pandas matplotlib

      - name: Run Scrapy spider
        run: |
          scrapy crawl multinews

      - name: Commit updated headlines.csv
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add headlines.csv
          git commit -m "Update headlines.csv [skip ci]" || echo "No changes to commit"
          git push
